#!/bin/sh

export WINEPATH="D:\\VC\\bin\\;D:\\bin\\"

cmd="all"
if [ $# -ne 0 ]
then
	cmd=$1
fi

if [ $cmd = "vbox" ]
then
	virtualboxvm --startvm COFUOS --start-running --debug &
	#--start-running --debug
	sleep 10s
	cd kernel/ && gdb
elif [ $cmd = "bochs" ]
then
	rm -f COFUOS.vhd.lock
	gnome-terminal -- bochs -q
	cd kernel/ && gdb
else
	export DEFINES=COFUOS
	make $@
fi

if [ $? -ne 0 ]
then
	echo Failed
else
	echo Success
fi
