#!/bin/sh

cmd=

if [ $# -ne 0 ]
then
	cmd=$1
fi

if [ $cmd = "vbox" ]
then
	virtualboxvm --startvm COFUOS &
	# --start-running --debug
	sleep 8s
	cd kernel/ && gdb
elif [ $cmd = "bochs" ]
then
	rm -f COFUOS.vhd.lock
	gnome-terminal -- bochs -q
	cd kernel/ && gdb
else
	false
fi

if [ $? -ne 0 ]
then
	echo Failed
else
	echo Success
fi
