#!/bin/sh

export WINEPATH="D:\\VC\\bin\\;D:\\bin\\"

cmd="all"
if [ $# -ne 0 ]
then
	cmd=$1
fi

if [ $cmd = "run" -o $cmd = "debug" ]
then
	cd tools/bochs
	wine cmd /c "${1}.bat"
else
	export DEFINES=
	. ./defines
	make $@
fi

if [ $? -ne 0 ]
then
	echo Failed
else
	echo Success
fi
